# Generated by Django 3.2.8 on 2024-08-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addres', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('delivery_status', models.CharField(choices=[('PEN', 'Pending'), ('DEL', 'Delivered')], default='PEN', max_length=3)),
                ('pizza_order', models.ManyToManyField(to='pizza.PizzaModel')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'ORDER',
            },
        ),
    ]
